"""Judge Agent resolves Evidence/Skeptic disagreement."""

from __future__ import annotations

import json

from pydantic import BaseModel, Field, ValidationError

from backend.models.schemas import AgentArgument, Claim, EvidenceItem, ModelUsage, Verdict, VerdictType
from backend.services.llm import LLMClient, LLMError


class JudgeAgentResult(BaseModel):
    verdict: Verdict | None = None
    usage: ModelUsage | None = None
    warning: str | None = None


class _Output(BaseModel):
    verdict: VerdictType
    confidence: float = Field(ge=0, le=1)
    support_score: int = Field(ge=0, le=100)
    lineage_score: int = Field(ge=0, le=100)
    reason: str = Field(min_length=1, max_length=700)
    supporting_evidence: list[str] = Field(default_factory=list, max_length=3)
    contradicting_evidence: list[str] = Field(default_factory=list, max_length=3)
    limitations: list[str] = Field(default_factory=list, max_length=3)


_PROMPT = """You are EvidenceLineage's Judge Agent. Resolve the Evidence and Skeptic
arguments against the supplied passages. Choose SUPPORTED, PARTIALLY_SUPPORTED, OVERSTATED,
CONTRADICTED, UNSUPPORTED, or INSUFFICIENT_EVIDENCE. Confidence is an uncalibrated model
estimate. Cite only supplied evidence IDs and never fill evidence gaps with assumptions.
Return only JSON with verdict, confidence, reason, supporting_evidence,
contradicting_evidence, limitations, support_score, and lineage_score. support_score is 0-100 and measures
how directly and completely the retrieved cited evidence supports the claim: 0 means no
support or contradiction, 50 means partial/conditional support, and 100 means direct support
with matching scope, conditions, and magnitude. lineage_score is 0-100 and measures how well
the cited paper's claim is backed by its retrieved upstream references. Use a low score when
upstream evidence is contradictory and 50 or below when only weak/insufficient upstream
abstract evidence is available. Keep reason under 100 words and each limitation under 25 words."""


async def judge_claim(
    claim: Claim,
    evidence: list[EvidenceItem],
    support: AgentArgument | None,
    skeptic: AgentArgument | None,
    client: LLMClient | None,
) -> JudgeAgentResult:
    if not evidence or support is None or skeptic is None:
        return JudgeAgentResult(
            verdict=Verdict(
                verdict=VerdictType.INSUFFICIENT_EVIDENCE,
                confidence=0,
                reason="Evidence or an independent agent argument was unavailable.",
                limitations=["This is a workflow failure state, not a scientific conclusion."],
            ),
            warning="Judge returned a workflow fallback because both agent arguments were not available.",
        )
    if client is None:
        return JudgeAgentResult(warning="No language model is configured for Judge Agent analysis.")
    allowed_ids = {item.id for item in evidence}
    prompt = json.dumps({
        "claim": claim.model_dump(), "evidence": [item.model_dump() for item in evidence],
        "evidence_agent": support.model_dump(), "skeptic_agent": skeptic.model_dump(),
    }, ensure_ascii=False)
    try:
        result = await client.generate(
            system_prompt=_PROMPT,
            user_prompt=prompt,
            json_schema=_Output.model_json_schema(),
        )
        parsed = _Output.model_validate_json(result.text)
        supporting = [item for item in parsed.supporting_evidence if item in allowed_ids]
        contradicting = [item for item in parsed.contradicting_evidence if item in allowed_ids]
        limitations = list(parsed.limitations)
        if set(parsed.supporting_evidence + parsed.contradicting_evidence) - allowed_ids:
            limitations.append("Unknown evidence IDs generated by the model were removed.")
        return JudgeAgentResult(
            verdict=Verdict(
                verdict=parsed.verdict,
                confidence=parsed.confidence,
                support_score=parsed.support_score,
                lineage_score=parsed.lineage_score,
                reason=parsed.reason,
                supporting_evidence=supporting,
                contradicting_evidence=contradicting,
                limitations=limitations,
            ),
            usage=ModelUsage(model=result.model, input_tokens=result.input_tokens, output_tokens=result.output_tokens),
        )
    except (LLMError, ValidationError, ValueError, json.JSONDecodeError) as exc:
        if isinstance(exc, ValidationError):
            message = exc.errors()[0].get("msg", "invalid structured output")
            return JudgeAgentResult(warning=f"Judge Agent returned invalid structured output: {message}.")
        return JudgeAgentResult(warning=f"Judge Agent failed safely: {type(exc).__name__}: {exc}")
